### ISSUE TITLE
pass.go can't compile

### ISSUE THREAD

**Issue by Course-Brains** [ksharnoff/pass#1]
When attempting to compile pass.go I got the error:
./pass.go:1442:89: too many arguments in call to print.WriteString
	have (string, string)
	want (string)
	
This is on the [v.1.2.0](https://github.com/ksharnoff/pass/releases/tag/v1.2.0) release

**Comment by ksharnoff** [comment]
Fixed with #[c27b5e4](https://github.com/ksharnoff/pass/commit/c27b5e4081980c497ad8e7544ded7a71dbc084c6)
